/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package projek;

/**
 *
 * @author ASUS
 */
public class PemesananTiket1 extends javax.swing.JFrame {

    /**
     * Creates new form Tiket
     */
    public PemesananTiket1() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroupjudulfilm = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtnama = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        RadioButtonMenInBlackInternational = new javax.swing.JRadioButton();
        RadioButtonBirdsofprey = new javax.swing.JRadioButton();
        RadioButtonShazam = new javax.swing.JRadioButton();
        RadioButtonMileaSuaradariDilan = new javax.swing.JRadioButton();
        RadioButtonTheSpongeBobMovie = new javax.swing.JRadioButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        Labelhari = new javax.swing.JLabel();
        Labeljamtayang = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(new javax.swing.border.MatteBorder(null));

        jLabel1.setText("Nama");

        jLabel2.setText("Judul Film");

        buttonGroupjudulfilm.add(RadioButtonMenInBlackInternational);
        RadioButtonMenInBlackInternational.setText("Men In Black: International");
        RadioButtonMenInBlackInternational.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RadioButtonMenInBlackInternationalActionPerformed(evt);
            }
        });

        buttonGroupjudulfilm.add(RadioButtonBirdsofprey);
        RadioButtonBirdsofprey.setText("Birds of Prey");
        RadioButtonBirdsofprey.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RadioButtonBirdsofpreyActionPerformed(evt);
            }
        });

        buttonGroupjudulfilm.add(RadioButtonShazam);
        RadioButtonShazam.setText("Shazam!");
        RadioButtonShazam.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RadioButtonShazamActionPerformed(evt);
            }
        });

        buttonGroupjudulfilm.add(RadioButtonMileaSuaradariDilan);
        RadioButtonMileaSuaradariDilan.setText("Milea: Suara dari Dilan");
        RadioButtonMileaSuaradariDilan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RadioButtonMileaSuaradariDilanActionPerformed(evt);
            }
        });

        buttonGroupjudulfilm.add(RadioButtonTheSpongeBobMovie);
        RadioButtonTheSpongeBobMovie.setText("The SpongeBob Movie");
        RadioButtonTheSpongeBobMovie.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RadioButtonTheSpongeBobMovieActionPerformed(evt);
            }
        });

        jLabel3.setText("Hari");

        jLabel4.setText("Jam tayang");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addGap(57, 57, 57)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(RadioButtonMenInBlackInternational)
                    .addComponent(txtnama, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(RadioButtonBirdsofprey)
                    .addComponent(RadioButtonShazam)
                    .addComponent(RadioButtonMileaSuaradariDilan)
                    .addComponent(RadioButtonTheSpongeBobMovie)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(79, 79, 79)
                        .addComponent(Labelhari, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(42, 42, 42)
                        .addComponent(Labeljamtayang, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(256, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtnama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(RadioButtonMenInBlackInternational, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(RadioButtonBirdsofprey, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(RadioButtonShazam, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(RadioButtonMileaSuaradariDilan, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(RadioButtonTheSpongeBobMovie, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(Labelhari, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(Labeljamtayang, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(218, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void RadioButtonMenInBlackInternationalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RadioButtonMenInBlackInternationalActionPerformed
        // TODO add your handling code here:
        String film = "";
        if(RadioButtonMenInBlackInternational.isSelected()){
            film = RadioButtonMenInBlackInternational.getText();
            Labelhari.setText("Senin");
            Labeljamtayang.setText("10.00-12.00");
        }
    }//GEN-LAST:event_RadioButtonMenInBlackInternationalActionPerformed

    private void RadioButtonBirdsofpreyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RadioButtonBirdsofpreyActionPerformed
        // TODO add your handling code here:
        String film = "";
        if(RadioButtonBirdsofprey.isSelected()){
            film = RadioButtonBirdsofprey.getText();
            Labelhari.setText("Senin");
            Labeljamtayang.setText("14.00-16.00");
        }
    }//GEN-LAST:event_RadioButtonBirdsofpreyActionPerformed

    private void RadioButtonShazamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RadioButtonShazamActionPerformed
        // TODO add your handling code here:
        String film = "";
        if(RadioButtonShazam.isSelected()){
            film = RadioButtonShazam.getText();
            Labelhari.setText("Senin");
            Labeljamtayang.setText("20.00-22.00");
        }
        
    }//GEN-LAST:event_RadioButtonShazamActionPerformed

    private void RadioButtonMileaSuaradariDilanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RadioButtonMileaSuaradariDilanActionPerformed
        // TODO add your handling code here:
        String film = "";
        if(RadioButtonMileaSuaradariDilan.isSelected()){
            film = RadioButtonMileaSuaradariDilan.getText();
            Labelhari.setText("Selasa");
            Labeljamtayang.setText("20.00-22.00");
        }
    }//GEN-LAST:event_RadioButtonMileaSuaradariDilanActionPerformed

    private void RadioButtonTheSpongeBobMovieActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RadioButtonTheSpongeBobMovieActionPerformed
        // TODO add your handling code here:
        String film = "";
        if(RadioButtonTheSpongeBobMovie.isSelected()){
            film = RadioButtonTheSpongeBobMovie.getText();
            Labelhari.setText("Selasa");
            Labeljamtayang.setText("13.00-15.00");
        }
    }//GEN-LAST:event_RadioButtonTheSpongeBobMovieActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PemesananTiket1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PemesananTiket1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PemesananTiket1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PemesananTiket1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PemesananTiket1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Labelhari;
    private javax.swing.JLabel Labeljamtayang;
    private javax.swing.JRadioButton RadioButtonBirdsofprey;
    private javax.swing.JRadioButton RadioButtonMenInBlackInternational;
    private javax.swing.JRadioButton RadioButtonMileaSuaradariDilan;
    private javax.swing.JRadioButton RadioButtonShazam;
    private javax.swing.JRadioButton RadioButtonTheSpongeBobMovie;
    private javax.swing.ButtonGroup buttonGroupjudulfilm;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField txtnama;
    // End of variables declaration//GEN-END:variables
}
