/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package projek;

/**
 *
 * @author ASUS
 */
public class PemesananTiket1 extends javax.swing.JFrame {

    /**
     * Creates new form Tiket
     */
    public PemesananTiket1() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroupjudulfilm = new javax.swing.ButtonGroup();
        buttonGroupjenistiket = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtnama = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        RadioButtonMenInBlackInternational = new javax.swing.JRadioButton();
        RadioButtonBirdsofprey = new javax.swing.JRadioButton();
        RadioButtonShazam = new javax.swing.JRadioButton();
        RadioButtonMileaSuaradariDilan = new javax.swing.JRadioButton();
        RadioButtonTheSpongeBobMovie = new javax.swing.JRadioButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        Labelhari = new javax.swing.JLabel();
        Labeljamtayang = new javax.swing.JLabel();
        RadioButtonaladdin2019 = new javax.swing.JRadioButton();
        RadioButtonthenightcomesforus = new javax.swing.JRadioButton();
        RadioButtonmoneyheist = new javax.swing.JRadioButton();
        RadioButtonoverthemoon = new javax.swing.JRadioButton();
        RadioButtonsonicthehedgehog = new javax.swing.JRadioButton();
        jLabel5 = new javax.swing.JLabel();
        txtkursi = new javax.swing.JTextField();
        txtjumlahtiket = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        Labelkursi1 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txttotalbayar = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txtuangbayar = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        buttonback = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(new javax.swing.border.MatteBorder(null));

        jLabel1.setText("Nama");

        jLabel2.setText("Judul Film");

        buttonGroupjudulfilm.add(RadioButtonMenInBlackInternational);
        RadioButtonMenInBlackInternational.setText("Men In Black: International");
        RadioButtonMenInBlackInternational.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RadioButtonMenInBlackInternationalActionPerformed(evt);
            }
        });

        buttonGroupjudulfilm.add(RadioButtonBirdsofprey);
        RadioButtonBirdsofprey.setText("Birds of Prey");
        RadioButtonBirdsofprey.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RadioButtonBirdsofpreyActionPerformed(evt);
            }
        });

        buttonGroupjudulfilm.add(RadioButtonShazam);
        RadioButtonShazam.setText("Shazam!");
        RadioButtonShazam.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RadioButtonShazamActionPerformed(evt);
            }
        });

        buttonGroupjudulfilm.add(RadioButtonMileaSuaradariDilan);
        RadioButtonMileaSuaradariDilan.setText("Milea: Suara dari Dilan");
        RadioButtonMileaSuaradariDilan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RadioButtonMileaSuaradariDilanActionPerformed(evt);
            }
        });

        buttonGroupjudulfilm.add(RadioButtonTheSpongeBobMovie);
        RadioButtonTheSpongeBobMovie.setText("The SpongeBob Movie");
        RadioButtonTheSpongeBobMovie.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RadioButtonTheSpongeBobMovieActionPerformed(evt);
            }
        });

        jLabel3.setText("Hari");

        jLabel4.setText("Jam tayang");

        buttonGroupjudulfilm.add(RadioButtonaladdin2019);
        RadioButtonaladdin2019.setText("Aladdin (2019)");
        RadioButtonaladdin2019.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RadioButtonaladdin2019ActionPerformed(evt);
            }
        });

        buttonGroupjudulfilm.add(RadioButtonthenightcomesforus);
        RadioButtonthenightcomesforus.setText("The Night Comes for Us");
        RadioButtonthenightcomesforus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RadioButtonthenightcomesforusActionPerformed(evt);
            }
        });

        buttonGroupjudulfilm.add(RadioButtonmoneyheist);
        RadioButtonmoneyheist.setText("Money Heist: The Phenomenon");
        RadioButtonmoneyheist.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RadioButtonmoneyheistActionPerformed(evt);
            }
        });

        buttonGroupjudulfilm.add(RadioButtonoverthemoon);
        RadioButtonoverthemoon.setText("Over The Moon");
        RadioButtonoverthemoon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RadioButtonoverthemoonActionPerformed(evt);
            }
        });

        buttonGroupjudulfilm.add(RadioButtonsonicthehedgehog);
        RadioButtonsonicthehedgehog.setText("Sonic The Hedgehog");
        RadioButtonsonicthehedgehog.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RadioButtonsonicthehedgehogActionPerformed(evt);
            }
        });

        jLabel5.setText("Kursi");

        jLabel6.setText("Jumlah tiket");

        jLabel7.setText("Jenis tiket");

        buttonGroupjenistiket.add(jRadioButton1);
        jRadioButton1.setText("Reguler");

        buttonGroupjenistiket.add(jRadioButton2);
        jRadioButton2.setText("VIP");

        Labelkursi1.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N

        jLabel8.setText("Total bayar");

        jLabel9.setText("Uang bayar");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6)
                    .addComponent(jLabel8)
                    .addComponent(jLabel9))
                .addGap(57, 57, 57)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(txtjumlahtiket, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel7)
                        .addGap(18, 18, 18)
                        .addComponent(jRadioButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jRadioButton2))
                    .addComponent(jLabel3)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(42, 42, 42)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Labelhari, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Labeljamtayang, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(txtuangbayar, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txttotalbayar, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtnama, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(RadioButtonMenInBlackInternational, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(RadioButtonBirdsofprey, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(RadioButtonShazam, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(RadioButtonMileaSuaradariDilan, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(RadioButtonTheSpongeBobMovie, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtkursi, javax.swing.GroupLayout.Alignment.LEADING))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(42, 42, 42)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(RadioButtonoverthemoon, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(RadioButtonaladdin2019, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(RadioButtonthenightcomesforus)
                                    .addComponent(RadioButtonmoneyheist)
                                    .addComponent(RadioButtonsonicthehedgehog, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(Labelkursi1, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(27, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel1)
                                    .addComponent(txtnama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel2)
                                    .addComponent(RadioButtonMenInBlackInternational, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(RadioButtonaladdin2019, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(RadioButtonBirdsofprey, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(RadioButtonthenightcomesforus, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(RadioButtonShazam, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(RadioButtonmoneyheist, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(RadioButtonMileaSuaradariDilan, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(RadioButtonoverthemoon, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(RadioButtonTheSpongeBobMovie, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(RadioButtonsonicthehedgehog, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addComponent(Labelhari, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Labeljamtayang, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(3, 3, 3))
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(txtjumlahtiket, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7)
                            .addComponent(jRadioButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jRadioButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtkursi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(Labelkursi1, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel8)
                    .addComponent(txttotalbayar, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(txtuangbayar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40))
        );

        jPanel2.setBackground(new java.awt.Color(255, 162, 3));

        buttonback.setText("Home");
        buttonback.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonbackActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(buttonback, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(buttonback)
                .addContainerGap(21, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(52, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void RadioButtonMenInBlackInternationalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RadioButtonMenInBlackInternationalActionPerformed
        // TODO add your handling code here:
        String film = "";
        if(RadioButtonMenInBlackInternational.isSelected()){
            film = RadioButtonMenInBlackInternational.getText();
            Labelhari.setText("Senin");
            Labeljamtayang.setText("10.00 - 12.00");
        }
    }//GEN-LAST:event_RadioButtonMenInBlackInternationalActionPerformed

    private void RadioButtonBirdsofpreyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RadioButtonBirdsofpreyActionPerformed
        // TODO add your handling code here:
        String film = "";
        if(RadioButtonBirdsofprey.isSelected()){
            film = RadioButtonBirdsofprey.getText();
            Labelhari.setText("Senin");
            Labeljamtayang.setText("14.00 - 16.00");
        }
    }//GEN-LAST:event_RadioButtonBirdsofpreyActionPerformed

    private void RadioButtonShazamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RadioButtonShazamActionPerformed
        // TODO add your handling code here:
        String film = "";
        if(RadioButtonShazam.isSelected()){
            film = RadioButtonShazam.getText();
            Labelhari.setText("Senin");
            Labeljamtayang.setText("20.00 - 22.00");
        }
        
    }//GEN-LAST:event_RadioButtonShazamActionPerformed

    private void RadioButtonMileaSuaradariDilanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RadioButtonMileaSuaradariDilanActionPerformed
        // TODO add your handling code here:
        String film = "";
        if(RadioButtonMileaSuaradariDilan.isSelected()){
            film = RadioButtonMileaSuaradariDilan.getText();
            Labelhari.setText("Selasa");
            Labeljamtayang.setText("20.00 - 22.00");
        }
    }//GEN-LAST:event_RadioButtonMileaSuaradariDilanActionPerformed

    private void RadioButtonTheSpongeBobMovieActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RadioButtonTheSpongeBobMovieActionPerformed
        // TODO add your handling code here:
        String film = "";
        if(RadioButtonTheSpongeBobMovie.isSelected()){
            film = RadioButtonTheSpongeBobMovie.getText();
            Labelhari.setText("Selasa");
            Labeljamtayang.setText("13.00 - 15.00");
        }
    }//GEN-LAST:event_RadioButtonTheSpongeBobMovieActionPerformed

    private void RadioButtonaladdin2019ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RadioButtonaladdin2019ActionPerformed
        // TODO add your handling code here:
        String film = "";
        if(RadioButtonaladdin2019.isSelected()){
            film = RadioButtonaladdin2019.getText();
            Labelhari.setText("Selasa");
            Labeljamtayang.setText("10.10 - 12.10");
        }
    }//GEN-LAST:event_RadioButtonaladdin2019ActionPerformed

    private void RadioButtonthenightcomesforusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RadioButtonthenightcomesforusActionPerformed
        // TODO add your handling code here:
        String film ="";
        if(RadioButtonthenightcomesforus.isSelected()){
            film = RadioButtonthenightcomesforus.getText();
            Labelhari.setText("Rabu");
            Labeljamtayang.setText("19.30 - 21.30");
        }
    }//GEN-LAST:event_RadioButtonthenightcomesforusActionPerformed

    private void RadioButtonmoneyheistActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RadioButtonmoneyheistActionPerformed
        // TODO add your handling code here:
        String film ="";
        if(RadioButtonmoneyheist.isSelected()){
            film = RadioButtonmoneyheist.getText();
            Labelhari.setText("Rabu");
            Labeljamtayang.setText("09.30 - 11.30");
        }
        
    }//GEN-LAST:event_RadioButtonmoneyheistActionPerformed

    private void RadioButtonoverthemoonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RadioButtonoverthemoonActionPerformed
        // TODO add your handling code here:
        String film ="";
        if(RadioButtonoverthemoon.isSelected()){
            film = RadioButtonoverthemoon.getText();
            Labelhari.setText("Rabu");
            Labeljamtayang.setText("14.30 - 16.30");
        }
    }//GEN-LAST:event_RadioButtonoverthemoonActionPerformed

    private void RadioButtonsonicthehedgehogActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RadioButtonsonicthehedgehogActionPerformed
        // TODO add your handling code here:
        String film ="";
        if(RadioButtonsonicthehedgehog.isSelected()){
            film = RadioButtonsonicthehedgehog.getText();
            Labelhari.setText("Kamis");
            Labeljamtayang.setText("10.00 - 12.00");
        }
    }//GEN-LAST:event_RadioButtonsonicthehedgehogActionPerformed

    private void buttonbackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonbackActionPerformed
        // TODO add your handling code here:
        homee hm = new homee();
        hm.setVisible(true);
        hm.setLocationRelativeTo(null);
        this.setVisible(false);
    }//GEN-LAST:event_buttonbackActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PemesananTiket1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PemesananTiket1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PemesananTiket1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PemesananTiket1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PemesananTiket1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Labelhari;
    private javax.swing.JLabel Labeljamtayang;
    private javax.swing.JLabel Labelkursi1;
    private javax.swing.JRadioButton RadioButtonBirdsofprey;
    private javax.swing.JRadioButton RadioButtonMenInBlackInternational;
    private javax.swing.JRadioButton RadioButtonMileaSuaradariDilan;
    private javax.swing.JRadioButton RadioButtonShazam;
    private javax.swing.JRadioButton RadioButtonTheSpongeBobMovie;
    private javax.swing.JRadioButton RadioButtonaladdin2019;
    private javax.swing.JRadioButton RadioButtonmoneyheist;
    private javax.swing.JRadioButton RadioButtonoverthemoon;
    private javax.swing.JRadioButton RadioButtonsonicthehedgehog;
    private javax.swing.JRadioButton RadioButtonthenightcomesforus;
    private javax.swing.ButtonGroup buttonGroupjenistiket;
    private javax.swing.ButtonGroup buttonGroupjudulfilm;
    private javax.swing.JButton buttonback;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JTextField txtjumlahtiket;
    private javax.swing.JTextField txtkursi;
    private javax.swing.JTextField txtnama;
    private javax.swing.JLabel txttotalbayar;
    private javax.swing.JTextField txtuangbayar;
    // End of variables declaration//GEN-END:variables
}
